import AppProvider from "@/components/AppProvider";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "../assets/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <AppProvider>
          <Header />
          <main className=" mx-auto px-4 min-h-screen">{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
